# Generated by Django 2.0.6 on 2018-06-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180610_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskall',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Finished')], default=0),
        ),
    ]
