# Generated by Django 2.0.6 on 2018-06-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180610_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskall',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Finished')], default=1),
        ),
    ]
